
DOMAIN = "concept2"
DEFAULT_UPDATE_INTERVAL_MIN = 120
INTERVAL_MIN = 5
INTERVAL_MAX = 1440
BASE_URL = "https://log.concept2.com"
LOGIN_URL = f"{BASE_URL}/login"
DASHBOARD_CANDIDATES = [f"{BASE_URL}/log"]
STORAGE_KEY = f"{DOMAIN}_state"
STORAGE_VERSION = 1
SENSOR_LIFETIME = "lifetime_meters"
SENSOR_DAY = "day_meters"
SENSOR_SEASON = "season_meters"
